# Generated by Django 2.2.19 on 2022-10-09 19:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20221009_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favotite',
            options={'verbose_name': 'Favorite'},
        ),
        migrations.AlterUniqueTogether(
            name='favotite',
            unique_together={('user', 'recipe')},
        ),
    ]
