# Generated by Django 2.2.19 on 2022-10-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221010_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=256, verbose_name='Measurement_unit'),
        ),
    ]
