# Generated by Django 2.2.19 on 2022-10-12 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_shoppingcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favotite',
            new_name='Favorite',
        ),
    ]
